name: Gitleaks Secret Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Gitleaks to scan for secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source=. --verbose --redact

      - name: Fail if secrets are found
        if: failure()
        run: |
          echo "❌ Secrets detected by Gitleaks!"
          exit 1
